### ISSUE TITLE
typePrice

### ISSUE THREAD

**Issue by zjsdss** [tianjingle/zMain#1]
你好。请问 typeprice 是什么参数。

**Comment by tianjingle** [comment]
均线里边有个典型价格，英文名称是typecalprice，之前发现这个指标具有一定的趋势特征，所以zmain就采用这个典型价格来作为计算数据。典型价格的计算公式：typeprice=(high+low+close)/3，在talib的相关函数是：TYPEPRICE(higt,low,close);您可以查阅资料详细了解一下这个典型价格。
